// <auto-generated />
using ECommerce_Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerce_Application.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200820010547_RemovedPostsSeed")]
    partial class RemovedPostsSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerce_Application.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperPower")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Breed = "Staffordshire Terrier",
                            Color = "Brindle",
                            Description = "Absolutely is an attention hog. He will chill and hang out with you all day and love life. He enjoys the outdoors from sunbathing in the backyard to going for long walks. Is very obedient and will let you clean his ears, brush ",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/Rampage",
                            Name = "Rampage",
                            Price = 200m,
                            SuperPower = "Super Love"
                        },
                        new
                        {
                            Id = 2,
                            Age = 4,
                            Breed = "Poodle",
                            Color = "White",
                            Description = "Loves ",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/Snowball",
                            Name = "Snowball",
                            Price = 200m,
                            SuperPower = "Super Love"
                        },
                        new
                        {
                            Id = 3,
                            Age = 7,
                            Breed = "Golden Doodle",
                            Color = "Golden",
                            Description = "Her thick hips won't stop her from dragging you across the concrete to catch a squirrel",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/Whiskey",
                            Name = "Whiskey",
                            Price = 2000m,
                            SuperPower = "Fly"
                        },
                        new
                        {
                            Id = 4,
                            Age = 6,
                            Breed = "Labradoodle",
                            Color = "black",
                            Description = "Fastest dog in the world. She's beat Usain Bolt... Twice. ",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/rye.jpeg",
                            Name = "Rye",
                            Price = 90000000m,
                            SuperPower = "Super speed"
                        },
                        new
                        {
                            Id = 5,
                            Age = 3,
                            Breed = "Dog",
                            Color = "Brown and White",
                            Description = "Will knock anything on your desk onto the floor. Can also poop in toilet. ",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/backup.jpeg",
                            Name = "Snowball",
                            Price = 40000m,
                            SuperPower = "Personality"
                        },
                        new
                        {
                            Id = 6,
                            Age = 15,
                            Breed = "Dog",
                            Color = "Brown",
                            Description = "Speaks English... And a little Spanish. ",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/Duke1.jpeg",
                            Name = "Duke",
                            Price = 9000m,
                            SuperPower = "Speaking"
                        },
                        new
                        {
                            Id = 7,
                            Age = 99,
                            Breed = "Dog",
                            Color = "Grey",
                            Description = "Disrupts Zoom meetings. Can order Starbucks on occassion.",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/Josie",
                            Name = "Josie",
                            Price = 6000000m,
                            SuperPower = "Ordering coffee"
                        },
                        new
                        {
                            Id = 8,
                            Age = 8,
                            Breed = "Dog",
                            Color = "Orangeish",
                            Description = "As if a dog wasn't enough, this guy comes with laser eyes. ",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/chubbs.jpeg",
                            Name = "Chubbs",
                            Price = 1000000m,
                            SuperPower = "Laser Eyes"
                        },
                        new
                        {
                            Id = 9,
                            Age = 15,
                            Breed = "Dog",
                            Color = "Orange and White",
                            Description = "An engineer who dabbles in explosives.",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/Peanut.jpeg",
                            Name = "Peanut",
                            Price = 500000m,
                            SuperPower = "Super Genius"
                        },
                        new
                        {
                            Id = 10,
                            Age = 6,
                            Breed = "Pomeranian",
                            Color = "Black",
                            Description = "Makes bukoo money.",
                            Image = "https://superpetpicturestorage.blob.core.windows.net/productimages/Mani",
                            Name = "Mani",
                            Price = 100000m,
                            SuperPower = "Can produce cash out of thin-air"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
